version: '3'
services:
  mongo:
    container_name: mongo-container
    networks:
      - mongo-api
    image: mongo:4
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    restart: always
  api:
    container_name: api-container
    build:
      context: .
    image: clean-node-api
    ports:
      - '4000:4000'
    command: yarn start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/api
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo-api
networks:
  mongo-api:
