name: Continuous Integration
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Get Current branch name
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/})"
        shell: bash
        id: branch
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn install
      - name: Lint
        run: yarn lint
      - name: Unit Tests
        run: yarn test:ci
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
